services:
  - type: web
    name: bookstore
    runtime: ruby
    buildCommand: "bundle install --without development:test && bundle exec rails assets:precompile"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore_db
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
databases:
  - name: bookstore_db
    databaseName: bookstore_db
    user: bookstore
    region: ohio
